"""add

Revision ID: ef167a41c084
Revises: 
Create Date: 2024-05-26 03:10:42.012679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef167a41c084'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_client', sa.String(), nullable=True),
    sa.Column('reference_month', sa.String(), nullable=True),
    sa.Column('electricity', sa.String(), nullable=True),
    sa.Column('sceee_energy_without_ICMS', sa.String(), nullable=True),
    sa.Column('compensated_energy_GD_I', sa.String(), nullable=True),
    sa.Column('contrib_municipal_public_light', sa.String(), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_client')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    # ### end Alembic commands ###
